# -*- coding: utf-8 -*-
"""Confusion Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1016QvUCB5ne0XoGQOVWAisGxUq0nVuj0
"""

import pandas as pd
import seaborn as sns
import numpy as np

from google.colab import drive
from google.colab import auth

drive.mount('/content/drive')

# read in nlcd data
bastrop_nlcd = pd.read_csv('/content/drive/MyDrive/bastrop_nlcd.csv')

bastrop_nlcd.columns

# crosstab dataframe
bast_matrix = pd.crosstab(bastrop_nlcd.b1, bastrop_nlcd.landcover)

"""**original model classes:**
0 = impervious,
1 = forest,
2 = water,
3 = field,
4 = bare
"""

bast_matrix

# heatmap 
bast_heatmap = sns.heatmap(bast_matrix, linewidths = .5)

# read in nlcd data
blanco_nlcd = pd.read_csv('/content/drive/MyDrive/blanco_nlcd.csv')

blanco_nlcd.columns

# crosstab dataframe
blanco_matrix = pd.crosstab(blanco_nlcd.b1, blanco_nlcd.landcover)
blanco_matrix

# read in nlcd data
caldwell_nlcd = pd.read_csv('/content/drive/MyDrive/caldwell_nlcd.csv')

caldwell_nlcd.columns

# crosstab dataframe
blanco_matrix = pd.crosstab(caldwell_nlcd.b1, caldwell_nlcd.landcover)
blanco_matrix

